# user:
#     resource: "@UserBundle/Resources/config/routing.yml"
#     prefix:   /Users

movie:
    resource: "@MovieBundle/Resources/config/routing.yml"
    prefix:   /movies

social:
    resource: "@SocialBundle/Resources/config/routing.yml"
    prefix:   /social

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation