<?php

namespace SocialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiketypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiketypeRepository extends EntityRepository
{
}
