<?php

namespace SocialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LikedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikedRepository extends EntityRepository
{
}
